main: {
    marginTop: "10vh",
    paddingTop: "10vh",
    height: "70vh",
    width: "100%",
    display: "flex",
    justifyContent: "space-around",
    alignItems: "start",
    background: "#F4F4F4",
  },
  card: {
    height: "50vh",
    width: "50vw",
    display: "flex",
    background: "white",
    padding: "1rem 2rem", 
  },
  card2: {
    height: "20vh",
    width: "27vw",
    display: "flex",
    flexDirection: "column",
    alignItems: "start",
    justifyContent: "space-around",
    background: "white",
    paddingLeft: "4vw",
    padding: "3vh 0",
  },
  heading: {
    fontSize: "2rem",
    display: "flex",
    alignItems: "center",
  },
  checkIcon: {
    color: "#53f000",
    marginRight: "0.5rem",
  },
  image: {
    height: "45vh",
    width: "20vw",
  },
  subDiv2: {
    marginLeft: "2rem",
  },
  backBtn: {
    textTransform: "none",
    display: "flex",
    alignItems: "center",
    justifyContent: "start",
    fontSize: "1.8rem",
    color: "#007185",
    "&:hover": {
      background: "transparent",
      textDecoration: "underline",
    },
  },
  buttonText: {
    fontSize: "1.6rem",
  },
  rupee: {
    fontSize: "1.1rem",
    display: "flex",
    alignItems: "center",
  },
  goToCart: {
    width: "18vw",
    padding: "0.2rem 0.3rem",
    borderRadius: "0.3rem",
    border: "1px solid lightgrey",
    cursor: "pointer",
    fontSize: "1rem",
    textAlign: "center",
    marginTop: "0.5rem",
    color: "black",
    boxShadow: "0.5px 0.5px 2px 0px grey",
    "&:hover": {
      background: "#F7FAFA",
    },
  },
  bottomButton: {
    height: "20vh",
  },
  link: {
    textDecoration: "none",
  },