main: {
    height: "58vh",
    width: "23vw",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    boxShadow: "none",
    marginTop: "2rem",
    borderRadius: "1rem",
    cursor: "pointer",
  },
  title: {
    height: "2rem",
    width: "90%",
    overflow: "hidden",
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
    marginTop: "0.5rem",
  },
  image: {
    height: "70%",
    width: "80%",
    marginTop: "0.5rem",
    backgroundRepeat: "no-repeat",
    backgroundSize: "100% 100%",
  },
  footer: {
    display: "flex",
    justifyContent: "space-between",
    width: "90%",
    background: "transparent",
  },
  addToCart: {
    background: "#FEBD69",
    height: "2rem",
    width: "8rem",
    borderRadius: "0.5rem",
    marginTop: "0.5rem",
    "&:hover": {
      background: "#FEBD69",
    },
  },
  rating: {
    display: "flex",
    alignItems: "center",
  },
  count: {
    marginLeft: "0.5rem",
    color: "#007185",
    fontSize: "1rem",
  },
  hoverText: {
    position: "relative",
    top: "50%",
    border: "1px solid grey",
    background: "#F7FAFA",
    width: "50%",
    margin: "auto",
    height: "2rem",
    borderRadius: "0.5rem",
    boxShadow: "0.5px 0.5px 2px 0px grey",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    "&:hover": {
      background: "#dcf4f7",
    },
  },